# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1905c9f83a4e6660284572d6af8aa124590749c8d300a48214b2c6d12b81f3a6aad9611808ac3a67f38a40c74d624dbfa5fe185acc92e3c204665c70b0650ad8

test:
  secret_key_base: 551df17e4102dd32bff2b3ef0057d84042035adf7bac7b4c4fb81ac00d4eb3a2f77c43e7ccf0c2b400a87bcca77a4295c6266b8fd2141d08761d952a06008125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
